### ISSUE TITLE
TODO for my til CLI

### ISSUE THREAD

**Issue by ahmedsaheed** [ahmedsaheed/TIL-CLI#1]
Start TIL CLI 

- [ ] Learn rust in an hour
- [ ] See MD support with rust
- [ ] Learn CLI proramming with rust
- [ ] Parse contents of til in MD

**Comment by ahmedsaheed** [comment]
TO DO 

- [ ] Collect user input
- [ ] POST to whervere (GitHub Gist For now)
- [ ] On completion of above **Parse inputed data to MD**
- [ ] And Repost
